version: '3.3'
services:
  api:
    build: ./backend/
    container_name: api
    ports:
        - "8000:80"
  frontend:
    container_name: frontend
    build: ./frontend/
    ports:
      - "80:80"
